import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home( {data}) {
  
  // function to update price by fetching api data 
  const updatePrice = async () => {
    const response = await fetch("https://api.abyiss.com/v1/coinbasepro/BTC-USD/currentprice?apiKey=ME1PQc(B25r2j10)2Vf91S)Q6P5cs2(lq3Z")
    const object = await response.json()
    document.getElementById('price').innerHTML= `${object.price.toLocaleString('en', { style: 'currency', currency: 'USD' })}`;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Bitcoin Price Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/> 
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/> 
        <link href="https://fonts.googleapis.com/css2?family=Kaisei+Decol&family=Prociono&display=swap" rel="stylesheet"/>
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <span>The Current Price of</span> <br></br> {/* line break here*/}
          {' '} 
          <span className={styles.logo}>
            <Image src="/bitcoin.png" alt="Bitcoin Logo" width={70} height={70} />
          </span>
          itcoin <span>is:</span>
          
        </div>

        <div className={styles.description}>
          <h1 id={styles.price}>{data.price.toLocaleString('en', { style: 'currency', currency: 'USD' })}
          </h1>
          
          {/* refreshes price using updatePrice function on button click*/}
          <button className={styles.button_81} onClick={updatePrice}>
            Refresh
          </button>
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://abyiss.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Used API from{' '}
          <span className={styles.logo}>
            <Image src="/abyiss.jpg" alt="Abyiss Logo" width={30} height={30} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// Fetches API data at request time and prerenders on page
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://api.abyiss.com/v1/coinbasepro/BTC-USD/currentprice?apiKey=ME1PQc(B25r2j10)2Vf91S)Q6P5cs2(lq3Z`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}
